import * as d3 from 'd3';
import './style.css';

declare global { interface Window { __VIS_READY__?: boolean; __INTERACTION_COUNT__?: number } }
const W=1400,H=900,scene=new URLSearchParams(location.search).get('scene')??'chord';
const svg=d3.select('#app').append('svg').attr('id','stage').attr('viewBox',`0 0 ${W} ${H}`).attr('width',W).attr('height',H);
const palette=['#54d6c6','#ffd166','#ff6f91','#7b9cff','#b889ff','#65b9ff'];
function heading(title:string,sub:string){svg.append('text').attr('x',72).attr('y',78).attr('class','title').text(title);svg.append('text').attr('x',74).attr('y',112).attr('class','subtitle').text(sub);svg.append('line').attr('x1',74).attr('x2',370).attr('y1',137).attr('y2',137).attr('stroke','#496b82')}
function chordScene(){
  heading('CIVIC EXCHANGE','FLOWS BETWEEN SIX URBAN COMMONS');
  const matrix=[[0,18,6,11,4,8],[14,0,15,5,8,6],[7,12,0,18,9,4],[10,4,16,0,13,7],[6,8,7,12,0,17],[11,5,3,8,15,0]];const names=['Culture','Mobility','Food','Learning','Care','Energy'];
  const chord=d3.chord().padAngle(.055).sortSubgroups(d3.descending)(matrix),arc=d3.arc<d3.ChordGroup>().innerRadius(270).outerRadius(300),ribbon=d3.ribbon<d3.Chord, d3.ChordSubgroup>().radius(266);
  const g=svg.append('g').attr('transform','translate(760,485)');
  g.append('g').selectAll('path').data(chord).join('path').attr('d',ribbon).attr('fill',d=>palette[d.source.index]).attr('fill-opacity',.28).attr('stroke',d=>palette[d.source.index]).attr('stroke-opacity',.65).attr('stroke-width',1.4);
  const groups=g.append('g').selectAll('g').data(chord.groups).join('g');groups.append('path').attr('d',arc).attr('fill',d=>palette[d.index]).attr('fill-opacity',.88).attr('stroke','#dff7ff').attr('stroke-opacity',.55);
  groups.append('text').attr('dy','.35em').attr('transform',d=>{const angle=(d.startAngle+d.endAngle)/2;return `rotate(${angle*180/Math.PI-90}) translate(325) ${angle>Math.PI?'rotate(180)':''}`}).attr('text-anchor',d=>(d.startAngle+d.endAngle)/2>Math.PI?'end':'start').attr('class','label').text(d=>names[d.index]);
  g.append('circle').attr('r',205).attr('fill','none').attr('stroke','#7692aa').attr('stroke-dasharray','2 9').attr('opacity',.42);
}
function treeScene(){
  heading('MYCELIUM ATLAS','A RADIAL TAXONOMY OF HIDDEN NETWORKS');
  const data={name:'Mycelium',children:['Signal','Exchange','Memory','Repair','Frontier'].map((n,i)=>({name:n,children:Array.from({length:4},(_,j)=>({name:`${n.slice(0,3)}-${j+1}`,children:j%2?[{name:`spore ${i+1}.${j}`}]:undefined}))}))};
  const root:any=d3.hierarchy(data),layout:any=d3.tree().size([Math.PI*2,340]).separation((a:any,b:any)=>(a.parent===b.parent?1:1.7)/a.depth);layout(root);
  const g=svg.append('g').attr('transform','translate(770,490)');const point=(d:any):[number,number]=>[Math.cos(d.x-Math.PI/2)*d.y,Math.sin(d.x-Math.PI/2)*d.y];
  g.selectAll('circle.guide').data([85,165,245,335]).join('circle').attr('r',d=>d).attr('fill','none').attr('stroke',(_,i)=>palette[i]).attr('stroke-width',18).attr('stroke-opacity',.16);
  g.selectAll('path.link').data(root.links()).join('path').attr('fill','none').attr('stroke',(d:any)=>palette[(d.target.depth+(d.target.data.name.length??0))%palette.length]).attr('stroke-opacity',.42).attr('stroke-width',(d:any)=>5-d.target.depth).attr('d',(d:any)=>{const s=point(d.source),t=point(d.target);return d3.linkRadial<any,any>().angle(x=>x.x).radius(x=>x.y)({source:d.source,target:d.target})??`M${s}L${t}`});
  const nodes=g.selectAll('g.node').data(root.descendants()).join('g').attr('transform',(d:any)=>`translate(${point(d)})`);nodes.append('circle').attr('r',(d:any)=>d.depth===0?24:8-d.depth).attr('fill',(d:any)=>d.depth===0?'#ffd166':palette[(d.depth+d.data.name.length)%palette.length]).attr('stroke','#e8f8ff').attr('stroke-opacity',.7);
  nodes.filter((d:any)=>d.depth<3).append('text').attr('x',(d:any)=>d.x<Math.PI?-12:12).attr('text-anchor',(d:any)=>d.x<Math.PI?'end':'start').attr('class','label').attr('font-size',(d:any)=>18-d.depth*2).text((d:any)=>d.data.name);
}
function voronoiScene(){
  heading('CLIMATE VORONOI','SYNTHETIC SENSOR TERRITORIES / 84 STATIONS');
  const points=Array.from({length:84},(_,i):[number,number]=>[120+((i*137)%1130)+35*Math.sin(i*2.4),175+((i*83)%610)+25*Math.cos(i*1.7)]);const delaunay=d3.Delaunay.from(points),v=delaunay.voronoi([70,160,1330,840]);
  const values=points.map(([x,y],i)=>.5+.28*Math.sin(x*.009)+.22*Math.cos(y*.013+i*.21));const scale=d3.scaleSequential(d3.interpolateTurbo).domain([0,1]);
  svg.append('g').selectAll('path').data(points).join('path').attr('d',(_,i)=>v.renderCell(i)).attr('fill',(_,i)=>scale(values[i])).attr('fill-opacity',.22).attr('stroke',(_,i)=>scale(values[i])).attr('stroke-opacity',.82).attr('stroke-width',1.2);
  svg.append('g').selectAll('circle').data(points).join('circle').attr('cx',d=>d[0]).attr('cy',d=>d[1]).attr('r',(_,i)=>2+values[i]*4).attr('fill',(_,i)=>scale(values[i])).attr('stroke','#f2fbff').attr('stroke-opacity',.55);
  const legend=svg.append('g').attr('transform','translate(1090,95)');d3.range(90).forEach(i=>legend.append('rect').attr('x',i*2).attr('width',2).attr('height',8).attr('fill',scale(i/89)));legend.append('text').attr('x',0).attr('y',-8).attr('class','micro').text('COOL');legend.append('text').attr('x',180).attr('y',-8).attr('text-anchor','end').attr('class','micro').text('WARM');
}
function forceNetwork(){heading('INSTITUTE COLLABORATION FIELD','COMMUNITIES, BRIDGES, AND REPEATED PARTNERSHIPS');const nodes=Array.from({length:58},(_,i):any=>({id:i,g:i%6,r:5+(i*13)%10}));const links=nodes.flatMap((n:any,i)=>[1,4,11].filter(k=>i+k<nodes.length&&(i+k)%5!==0).map(k=>({source:i,target:i+k})));const sim=d3.forceSimulation(nodes).force('link',d3.forceLink(links).id((d:any)=>d.id).distance(42)).force('charge',d3.forceManyBody().strength(-95)).force('center',d3.forceCenter(760,490)).force('collide',d3.forceCollide((d:any)=>d.r+6)).stop();for(let i=0;i<300;i++)sim.tick();svg.append('g').selectAll('circle.halo').data(d3.range(6)).join('circle').attr('cx',d=>535+(d%3)*220).attr('cy',d=>340+Math.floor(d/3)*300).attr('r',125).attr('fill',d=>palette[d]).attr('fill-opacity',.11).attr('stroke',d=>palette[d]).attr('stroke-opacity',.18);svg.append('g').selectAll('line').data(links).join('line').attr('x1',(d:any)=>d.source.x).attr('y1',(d:any)=>d.source.y).attr('x2',(d:any)=>d.target.x).attr('y2',(d:any)=>d.target.y).attr('stroke','#7694aa').attr('stroke-opacity',.25);svg.append('g').selectAll('circle').data(nodes).join('circle').attr('cx',(d:any)=>d.x).attr('cy',(d:any)=>d.y).attr('r',(d:any)=>d.r).attr('fill',(d:any)=>palette[d.g]).attr('fill-opacity',.78).attr('stroke','#eaf8ff').attr('stroke-opacity',.5);}
function treemapScene(){heading('HABITAT LOSS TREEMAP','BIOMES → DRIVERS → OBSERVED PRESSURE');const data={name:'Earth',children:['Forest','Wetland','Grassland','Coast'].map((n,i)=>({name:n,children:['Conversion','Heat','Pollution','Fragmentation'].map((d,j)=>({name:d,value:18+((i+2)*(j+3)*13)%58}))}))};const root=d3.hierarchy(data).sum((d:any)=>d.value??0);d3.treemap<any>().size([1180,650]).paddingOuter(7).paddingTop(28).paddingInner(4)(root as any);const g=svg.append('g').attr('transform','translate(120,170)');const leaves=g.selectAll('g').data(root.leaves()).join('g').attr('transform',(d:any)=>`translate(${d.x0},${d.y0})`);leaves.append('rect').attr('width',(d:any)=>d.x1-d.x0).attr('height',(d:any)=>d.y1-d.y0).attr('rx',9).attr('fill',(d:any)=>palette[(d.parent?.data?.name?.length??0)%5]).attr('fill-opacity',(d:any)=>.28+.08*((d.data.value??0)%4)).attr('stroke',(d:any)=>palette[(d.parent?.data?.name?.length??0)%5]);leaves.append('text').attr('x',12).attr('y',22).attr('class','label').text((d:any)=>d.data.name);g.selectAll('text.parent').data(root.children??[]).join('text').attr('x',(d:any)=>d.x0+10).attr('y',(d:any)=>d.y0+20).attr('class','subtitle').text((d:any)=>d.data.name.toUpperCase());}
function sunburstScene(){heading('SOFTWARE SYSTEM SUNBURST','PRODUCT → DOMAIN → MODULE → RESPONSIBILITY');const data={name:'System',children:['Experience','Platform','Intelligence','Operations'].map((n,i)=>({name:n,children:Array.from({length:4},(_,j)=>({name:['Core','Data','API','Runtime'][j],children:Array.from({length:3},(_,k)=>({name:`${n.slice(0,3)}-${j+1}.${k+1}`,value:4+((i+j+k)*7)%14}))}))}))};const root=d3.partition<any>().size([2*Math.PI,350])(d3.hierarchy(data).sum((d:any)=>d.value??0));const arc=d3.arc<any>().startAngle(d=>d.x0).endAngle(d=>d.x1).innerRadius(d=>d.y0).outerRadius(d=>d.y1-3).padAngle(.006).cornerRadius(4);const g=svg.append('g').attr('transform','translate(760,495)');g.selectAll('path').data(root.descendants().filter(d=>d.depth)).join('path').attr('d',arc).attr('fill',d=>palette[(d.ancestors().at(-2)?.children?.indexOf(d.ancestors().at(-2) as any)??d.depth)%5]).attr('fill-opacity',d=>.28+d.depth*.16).attr('stroke','#0c1a2c');g.selectAll('text').data(root.descendants().filter(d=>d.depth<3&&d.x1-d.x0>.16)).join('text').attr('transform',d=>`rotate(${(d.x0+d.x1)/2*180/Math.PI-90}) translate(${(d.y0+d.y1)/2},0) rotate(${(d.x0+d.x1)/2>Math.PI?180:0})`).attr('class','label').attr('font-size',11).attr('text-anchor','middle').text(d=>d.data.name);}
function streamgraph(){heading('A DAY OF LISTENING','COMPOSITION OF SIX MODES ACROSS 96 INTERVALS');const data=Array.from({length:96},(_,i)=>Object.fromEntries([['t',i],...Array.from({length:6},(_,j):[string,number]=>[`v${j}`,12+9*Math.sin(i*.09+j)+7*Math.cos(i*.037*(j+1))+((i*j+7)%8)])]));const keys=Array.from({length:6},(_,i)=>`v${i}`),stack=d3.stack<any>().keys(keys).offset(d3.stackOffsetWiggle).order(d3.stackOrderInsideOut)(data);const x=d3.scaleLinear().domain([0,95]).range([100,1320]),y=d3.scaleLinear().domain([d3.min(stack,l=>d3.min(l,d=>d[0]))!,d3.max(stack,l=>d3.max(l,d=>d[1]))!]).range([780,180]);const area=d3.area<any>().x((_,i)=>x(i)).y0(d=>y(d[0])).y1(d=>y(d[1])).curve(d3.curveBasis);svg.selectAll('path.stream').data(stack).join('path').attr('d',area).attr('fill',(_,i)=>palette[i]).attr('fill-opacity',.6).attr('stroke',(_,i)=>palette[i]).attr('stroke-width',1);for(let h=0;h<=24;h+=4){const X=x(h*4);svg.append('line').attr('x1',X).attr('x2',X).attr('y1',160).attr('y2',800).attr('stroke','#7895aa').attr('opacity',.18);svg.append('text').attr('x',X).attr('y',830).attr('text-anchor','middle').attr('class','micro').text(`${String(h).padStart(2,'0')}:00`)}}
function matrixScene(){heading('COLLABORATION MATRIX','ASYMMETRIC EXCHANGE BETWEEN TWELVE TEAMS');const names=['Bio','Civic','Data','Earth','Field','Geo','Health','Infra','Lab','Media','Policy','Robotics'],cell=48,ox=420,oy=205;const vals=names.flatMap((_,y)=>names.map((__,x)=>x===y?0:((x*17+y*29+x*y*3)%100)));svg.append('g').selectAll('rect').data(vals).join('rect').attr('x',(_,i)=>ox+(i%12)*cell).attr('y',(_,i)=>oy+Math.floor(i/12)*cell).attr('width',cell-3).attr('height',cell-3).attr('rx',5).attr('fill',d=>d===0?'transparent':d3.interpolateTurbo(.12+d/130)).attr('fill-opacity',d=>d===0?0:.25+d/160).attr('stroke','#4e6c83').attr('stroke-opacity',.28);names.forEach((n,i)=>{svg.append('text').attr('x',ox-14).attr('y',oy+i*cell+30).attr('text-anchor','end').attr('class','label').text(n);svg.append('text').attr('transform',`translate(${ox+i*cell+28},${oy-15}) rotate(-50)`).attr('class','label').text(n)});}
function beeswarm(){heading('BENCHMARK DISTRIBUTIONS','EVERY RUN REMAINS VISIBLE / N = 360');const groups=['Parser','Planner','Runtime','Storage'],data=groups.flatMap((g,j)=>Array.from({length:90},(_,i):any=>({g,j,v:45+j*18+Math.sin(i*1.7+j)*18+(i*13)%17,x:0,y:0})));const x=d3.scaleLinear().domain([20,140]).range([180,1280]);groups.forEach((g,j)=>{const subset=data.filter(d=>d.j===j);const sim=d3.forceSimulation(subset).force('x',d3.forceX((d:any)=>x(d.v)).strength(1)).force('y',d3.forceY(260+j*145).strength(.2)).force('collide',d3.forceCollide(7)).stop();for(let k=0;k<180;k++)sim.tick();svg.append('text').attr('x',80).attr('y',266+j*145).attr('class','label').text(g);svg.append('g').selectAll('circle').data(subset).join('circle').attr('cx',(d:any)=>d.x).attr('cy',(d:any)=>d.y).attr('r',6).attr('fill',palette[j]).attr('fill-opacity',.72)});}
function slopegraph(){heading('REGIONAL RANK REVERSALS','CHANGE BETWEEN 2016 AND 2026');const regions=['North','Coast','Delta','Highland','Metro','Rural','Island','Frontier'],left=[82,38,67,51,90,44,73,59],right=[61,72,48,86,77,63,42,91],y=d3.scaleLinear().domain([30,100]).range([760,210]);svg.append('line').attr('x1',400).attr('x2',400).attr('y1',180).attr('y2',790).attr('stroke','#66859b').attr('stroke-width',2);svg.append('line').attr('x1',1040).attr('x2',1040).attr('y1',180).attr('y2',790).attr('stroke','#66859b').attr('stroke-width',2);regions.forEach((n,i)=>{const c=palette[i%5];svg.append('line').attr('x1',400).attr('x2',1040).attr('y1',y(left[i])).attr('y2',y(right[i])).attr('stroke',c).attr('stroke-width',6).attr('stroke-opacity',.78);svg.append('circle').attr('cx',400).attr('cy',y(left[i])).attr('r',10).attr('fill',c);svg.append('circle').attr('cx',1040).attr('cy',y(right[i])).attr('r',10).attr('fill',c);svg.append('text').attr('x',380).attr('y',y(left[i])+5).attr('text-anchor','end').attr('class','label').text(`${n} ${left[i]}`);svg.append('text').attr('x',1060).attr('y',y(right[i])+5).attr('class','label').text(`${right[i]} ${n}`)});}
function contourScene(){heading('PRESSURE SYSTEM INTERFERENCE','TWO SYNTHETIC FIELDS / 18 ISO-LEVELS');const w=160,h=90,values=Array.from({length:w*h},(_,i)=>{const x=i%w,y=Math.floor(i/w);return 55*Math.exp(-((x-55)**2+(y-40)**2)/700)+48*Math.exp(-((x-112)**2+(y-55)**2)/850)+12*Math.sin(x*.15)*Math.cos(y*.2)});const contours=d3.contours().size([w,h]).thresholds(d3.range(4,74,4))(values);const proj=d3.geoPath(d3.geoIdentity().scale(7.1).translate([120,160]));svg.append('g').selectAll('path').data(contours).join('path').attr('d',proj as any).attr('fill',(d,i)=>d3.interpolateTurbo(.12+i/22)).attr('fill-opacity',.08).attr('stroke',(d,i)=>d3.interpolateTurbo(.12+i/22)).attr('stroke-width',1.4);}
function spiralScene(){heading('SEASONAL SPIRAL','SEVEN YEARS OF CYCLICAL DEMAND');const cx=760,cy=490,points=Array.from({length:365*7},(_,i):[number,number]=>{const a=i/365*Math.PI*2-Math.PI/2,r=70+i*.105+28*Math.sin(i/365*Math.PI*2);return[cx+Math.cos(a)*r,cy+Math.sin(a)*r]});const path=d3.line().curve(d3.curveCatmullRom)(points);svg.append('path').attr('d',path).attr('fill','none').attr('stroke','url(#spiral-gradient)').attr('stroke-width',5).attr('stroke-opacity',.72);const defs=svg.append('defs'),grad=defs.append('linearGradient').attr('id','spiral-gradient');palette.forEach((c,i)=>grad.append('stop').attr('offset',`${i*20}%`).attr('stop-color',c));for(let year=0;year<7;year++){const p=points[year*365];svg.append('circle').attr('cx',p[0]).attr('cy',p[1]).attr('r',8).attr('fill',palette[year%5]);svg.append('text').attr('x',p[0]+14).attr('y',p[1]).attr('class','micro').text(String(2020+year))}}
const renderers:Record<string,()=>void>={chord:chordScene,'radial-tree':treeScene,voronoi:voronoiScene,'force-network':forceNetwork,treemap:treemapScene,sunburst:sunburstScene,streamgraph,matrix:matrixScene,beeswarm,slopegraph,contours:contourScene,spiral:spiralScene};
(renderers[scene]??chordScene)();
window.__INTERACTION_COUNT__=0;svg.on('pointermove',()=>window.__INTERACTION_COUNT__=(window.__INTERACTION_COUNT__??0)+1).on('pointerdown',()=>window.__INTERACTION_COUNT__=(window.__INTERACTION_COUNT__??0)+1);window.__VIS_READY__=true;
